### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by sFreezer** [rcardin/assertj-arrow-core#21]
Hey @rcardin,
I tried to publish the version on maven, but failed because I don't have the rights to push to this repo.

**mvn release:prepare** (failed by doing this -> )
'git' 'push' 'ssh://github.com:rcardin/assertj-arrow-core.git' 'refs/heads/main:refs/heads/main'

**Comment by sFreezer** [comment]
is it possible for you to relate it ?

**Comment by rcardin** [comment]
@sFreezer, you can't publish on Maven. It's a pleasure that I reserve for myself :P 

For this reason, I asked you if you have an ETA concerning the feature you added.

**Comment by rcardin** [comment]
Released v. 0.1.0.
