### ISSUE TITLE
Add assertions for `NonEmptyList<A>` type

### ISSUE THREAD

**Issue by rcardin** [rcardin/assertj-arrow-core#31]
Add assertions for `NonEmptyList<A>` type. As an example, take a look at the assertions list implemented by [Kotest](https://kotest.io/docs/assertions/arrow.html) library for such type.

| NonEmptyList |  |
-- | --
| `nel.shouldContain(e)` | Asserts that the NonEmptyList contains the given element e |
| `nel.shouldContainAll(e1,e2,...,en)` | Asserts that the NonEmptyList contains all the given elements e1,e2,...,en |
| `nel.shouldContainNull()` | Asserts that the NonEmptyList contains at least one null |
| `nel.shouldContainNoNulls()` | Asserts that the NonEmptyList contains no nulls |
| `nel.shouldContainOnlyNulls()` | Asserts that the NonEmptyList contains only nulls or is empty |
| `nel.shouldHaveDuplicates()` | Asserts that the NonEmptyList has at least one duplicate |
| `nel.shouldBeSingleElement(e)` | Asserts that the NonEmptyList has a single element which is e |
| `nel.shouldBeSorted()` | Asserts that the NonEmptyList is sorted |

**Comment by farajist** [comment]
This seems interesting @rcardin, I will give it a shot if you haven't already started on it :slightly_smiling_face:, it's been a while

**Comment by rcardin** [comment]
Hey, man. Yep, if you want, it’s yours. Let me know.

Cheers

**Comment by farajist** [comment]
Let's gooo :rocket: ! Thanks @rcardin :)
