### ISSUE TITLE
Satisfies with consumer for multiple assertions syntax doesn't work

### ISSUE THREAD

**Issue by TobseF** [rcardin/assertj-arrow-core#50]
I'm trying to work with the `AbstractAssert#satisfies(java.util.function.Consumer<? super ACTUAL>...)` to check multiple assertions.

The docs show this example:
``` kotlin
assertThat(team. getPlayers().get(0).getStats()).satisfies(stats -> assertThat(stats. pointPerGame).isGreaterThan(25.7),
                                                            stats -> assertThat(stats. assistsPerGame).isGreaterThan(7.2),
                                                            stats -> assertThat(stats. reboundsPerGame).isBetween(9, 12));
```
It would help to add it to the test cases. Because I'm not able to reproduce the syntax.

What I have tried:
``` kotlin
// ⚡ Does not compile: `Unexpected tokens`
val ok: Either<Nothing, String> = "OK".right()
assertThat(ok).isRight().satisfies(
     s -> assertThat(s).isNotNull ,
    s -> assertThat(s).isEqualTo("OK") 
)
```

What worked:
``` kotlin
 val ok: Either<Nothing, String> = "OK".right()
assertThat(ok).isRight().satisfies(
    { s -> assertThat(s).isNotNull },
    {s -> assertThat(s).isEqualTo("OK") }
)
```
Wrapping the calls wit `{ ... }` works. But this calls another method:  
`org.assertj.core.api.AbstractAssert#satisfies(org.assertj.core.api.ThrowingConsumer<? super ACTUAL>...)`  
and not the mentioned with the `Consumer`. It's also not equal with the supped syntax.

Is the overloading ambiguous, do I use it wrong, or is the documentation incorrect?

**Comment by rcardin** [comment]
Thanks for the feedback 🙇 ! I'll check it in the next few days

**Comment by rcardin** [comment]
Hey, @TobseF. Again, thanks for the question. I checked. First, as far as I know, in Kotlin, lambdas must be enclosed into `{ ... }`. I also checked the two interfaces the `satisfies` method accepts. The `ThrowingConsumer<T>` extends the `Consumer<T>`. So, you can use the first everywhere you need an instance of the second.

Why the Kotlin compiler (or the IDE?) is selecting the `ThrowingConsumer<T>` overload of the `satisfies` method is relatively obscure to me. However, if you want to force the usage of the `Consumer` interface, you can specify it before the lambda:

```kotlin
val ok: Either<Nothing, String> = "OK".right()
assertThat(ok).isRight().satisfies(
    Consumer { s -> assertThat(s).isNotNull },
    Consumer {s -> assertThat(s).isEqualTo("OK") }
)
```

Hope it helps 🙂
